@startuml
header Express food
title Ajout d'un nouveau plat
actor Cuisinier
participant App
database Bdd
ref over Cuisinier, App, Bdd : Authentification
activate App
App -->> Cuisinier: Formulaire d'ajout de plat
Cuisinier -> App: Ajoute un nouveau plat
App -> App: verifie les informations
activate App
alt succès
App -> Bdd: enregistre le nouveau plat
deactivate App
App -->> Cuisinier: Nouveau plat ajouté
else echec
App -> Cuisinier: Erreur de Saisie
deactivate App
end
@enduml